config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get 'type' => 'application#type', :as => "type"
  get 'buttons' => 'application#buttons', :as => "buttons"
  get 'forms' => 'application#forms', :as => "forms"
  get 'modals' => 'application#modals', :as => "modals"
  get 'errors' => 'application#errors', :as => "errors"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<img src="<%= asset_path('logo.png') %>" id="logo"/>

app/views/application/type.html.erb
<% content_for :title, "Typography" %>

<h1>typography playground</h1>

<p>Some introduction paragraphs are longer than others, but the primary purpose of such a paragraph is to convey a blurb of what is to come. That being the case, since this page is about nothing, this paragraph effectively conveys nothing important or relevant about nothingness.</p>

<h2>use headers for good</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non lorem massa. Donec convallis est vel gravida ullamcorper. Etiam maximus elit vitae tempus dictum. Curabitur laoreet diam eu enim tincidunt, a faucibus enim pharetra. Ut convallis leo ligula, tempor faucibus nulla tincidunt et. Phasellus auctor fringilla libero feugiat finibus. Ut in laoreet orci, id auctor orci. Curabitur semper, magna quis commodo efficitur, turpis dui congue orci, egestas consectetur arcu orci vel massa. Pellentesque in auctor lectus. Suspendisse ultrices molestie turpis a lacinia. Donec est ex, vestibulum ut mi in, pharetra tincidunt nunc. Mauris nec dignissim augue. Quisque vel purus nibh. In dui tortor, lobortis sit amet aliquet quis, rhoncus a lectus. Duis id pellentesque risus. Cras malesuada urna a sagittis bibendum.</p>

<blockquote>"Beginnings of a true paragraph. Let's lipsum this up!"</blockquote>

<p>Etiam orci erat, bibendum vitae arcu quis, congue egestas justo. Praesent sagittis a purus at sollicitudin. Aliquam volutpat sed orci tempus condimentum. Vestibulum quam diam, bibendum commodo mi ut, elementum placerat mauris. Vivamus in odio arcu. Proin at odio blandit, hendrerit lacus sed, iaculis erat. Morbi laoreet lacus sit amet ex pulvinar, vitae maximus nulla lobortis. Integer interdum pulvinar leo eget commodo. Donec eget semper arcu. Pellentesque id neque diam. Sed malesuada eros nec urna mattis sollicitudin. Suspendisse consectetur lorem id nisi sodales iaculis.</p>

<h3>This list's header</h3>
<p>Etiam orci erat, bibendum vitae arcu quis, congue egestas justo. Praesent sagittis a purus at sollicitudin. Aliquam volutpat sed orci tempus condimentum.</p>
<ul>
    <li>First item in a list</li>
    <li>Second item in a list</li>
    <li>Third item in a list</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playground <%= @title %></title>
  <link rel="icon" href="<%= asset_path('favicon.png') %>"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="nav">
    <div class="center-wrap">
        <a href="<%= root_path %>">Home</a>
        <a href="<%= type_path %>">Typography</a>
        <a href="<%= buttons_path %>">Buttons</a>
        <a href="<%= forms_path %>">Forms</a>
        <a href="<%= modals_path %>">Modals</a>
        <a href="<%= errors_path %>">Errors/Alerts</a>
    </div>
    <div class="clearfix"></div>
</div>

<div class="center-wrap page-content">
    <%= yield %>
</div>

</body>
</html>